os:
    - linux

language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4

install:
    - python setup.py install

env:
    - TRAVIS_CI=TRAVIS_CI

script:
    # - python -m unittest discover